// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/gitlab.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Events        []string               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookConfig) Reset() {
	*x = WebhookConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookConfig) ProtoMessage() {}

func (x *WebhookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookConfig.ProtoReflect.Descriptor instead.
func (*WebhookConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WebhookConfig) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *WebhookConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebhookConfig) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WebhookConfig) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GitLabClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLabClientConfig) Reset() {
	*x = GitLabClientConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLabClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLabClientConfig) ProtoMessage() {}

func (x *GitLabClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLabClientConfig.ProtoReflect.Descriptor instead.
func (*GitLabClientConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{1}
}

func (x *GitLabClientConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitLabClientConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TriggerPipelineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerPipelineConfig) Reset() {
	*x = TriggerPipelineConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPipelineConfig) ProtoMessage() {}

func (x *TriggerPipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPipelineConfig.ProtoReflect.Descriptor instead.
func (*TriggerPipelineConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerPipelineConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TriggerPipelineConfig) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TriggerPipelineConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TriggerPipelineConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TriggerPipelineConfig) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type TriggerPipelineInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerPipelineInput) Reset() {
	*x = TriggerPipelineInput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPipelineInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPipelineInput) ProtoMessage() {}

func (x *TriggerPipelineInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPipelineInput.ProtoReflect.Descriptor instead.
func (*TriggerPipelineInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerPipelineInput) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TriggerPipelineInput) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TriggerPipelineInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TriggerPipelineInput) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type PipelineStatusConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	PipelineId    int32                  `protobuf:"varint,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStatusConfig) Reset() {
	*x = PipelineStatusConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStatusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStatusConfig) ProtoMessage() {}

func (x *PipelineStatusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStatusConfig.ProtoReflect.Descriptor instead.
func (*PipelineStatusConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{4}
}

func (x *PipelineStatusConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PipelineStatusConfig) GetPipelineId() int32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *PipelineStatusConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PipelineStatusConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PipelineStatusInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	PipelineId    int32                  `protobuf:"varint,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStatusInput) Reset() {
	*x = PipelineStatusInput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStatusInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStatusInput) ProtoMessage() {}

func (x *PipelineStatusInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStatusInput.ProtoReflect.Descriptor instead.
func (*PipelineStatusInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{5}
}

func (x *PipelineStatusInput) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PipelineStatusInput) GetPipelineId() int32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *PipelineStatusInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateMergeRequestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,2,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,3,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMergeRequestConfig) Reset() {
	*x = CreateMergeRequestConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMergeRequestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMergeRequestConfig) ProtoMessage() {}

func (x *CreateMergeRequestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMergeRequestConfig.ProtoReflect.Descriptor instead.
func (*CreateMergeRequestConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMergeRequestConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateMergeRequestConfig) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *CreateMergeRequestConfig) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *CreateMergeRequestConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMergeRequestConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMergeRequestConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateMergeRequestConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateMergeRequestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,2,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,3,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMergeRequestInput) Reset() {
	*x = CreateMergeRequestInput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMergeRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMergeRequestInput) ProtoMessage() {}

func (x *CreateMergeRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMergeRequestInput.ProtoReflect.Descriptor instead.
func (*CreateMergeRequestInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMergeRequestInput) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateMergeRequestInput) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *CreateMergeRequestInput) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *CreateMergeRequestInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMergeRequestInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMergeRequestInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MRCommentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	MrIid         int32                  `protobuf:"varint,2,opt,name=mr_iid,json=mrIid,proto3" json:"mr_iid,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRCommentConfig) Reset() {
	*x = MRCommentConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRCommentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRCommentConfig) ProtoMessage() {}

func (x *MRCommentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRCommentConfig.ProtoReflect.Descriptor instead.
func (*MRCommentConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{8}
}

func (x *MRCommentConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *MRCommentConfig) GetMrIid() int32 {
	if x != nil {
		return x.MrIid
	}
	return 0
}

func (x *MRCommentConfig) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MRCommentConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MRCommentConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MRCommentInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	MrIid         int32                  `protobuf:"varint,2,opt,name=mr_iid,json=mrIid,proto3" json:"mr_iid,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRCommentInput) Reset() {
	*x = MRCommentInput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRCommentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRCommentInput) ProtoMessage() {}

func (x *MRCommentInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRCommentInput.ProtoReflect.Descriptor instead.
func (*MRCommentInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{9}
}

func (x *MRCommentInput) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *MRCommentInput) GetMrIid() int32 {
	if x != nil {
		return x.MrIid
	}
	return 0
}

func (x *MRCommentInput) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MRCommentInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseWebhookConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseWebhookConfig) Reset() {
	*x = ParseWebhookConfig{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseWebhookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseWebhookConfig) ProtoMessage() {}

func (x *ParseWebhookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseWebhookConfig.ProtoReflect.Descriptor instead.
func (*ParseWebhookConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{10}
}

func (x *ParseWebhookConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ParseWebhookInput struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	EventType     string                     `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Body          *structpb.Struct           `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Fields        map[string]*structpb.Value `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseWebhookInput) Reset() {
	*x = ParseWebhookInput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseWebhookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseWebhookInput) ProtoMessage() {}

func (x *ParseWebhookInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseWebhookInput.ProtoReflect.Descriptor instead.
func (*ParseWebhookInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{11}
}

func (x *ParseWebhookInput) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ParseWebhookInput) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ParseWebhookInput) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PipelineOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    int32                  `protobuf:"varint,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Sha           string                 `protobuf:"bytes,4,opt,name=sha,proto3" json:"sha,omitempty"`
	WebUrl        string                 `protobuf:"bytes,5,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineOutput) Reset() {
	*x = PipelineOutput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineOutput) ProtoMessage() {}

func (x *PipelineOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineOutput.ProtoReflect.Descriptor instead.
func (*PipelineOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{12}
}

func (x *PipelineOutput) GetPipelineId() int32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *PipelineOutput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PipelineOutput) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *PipelineOutput) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *PipelineOutput) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

func (x *PipelineOutput) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PipelineOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MergeRequestOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MrId          int32                  `protobuf:"varint,1,opt,name=mr_id,json=mrId,proto3" json:"mr_id,omitempty"`
	MrIid         int32                  `protobuf:"varint,2,opt,name=mr_iid,json=mrIid,proto3" json:"mr_iid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,5,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,6,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	WebUrl        string                 `protobuf:"bytes,7,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequestOutput) Reset() {
	*x = MergeRequestOutput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequestOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequestOutput) ProtoMessage() {}

func (x *MergeRequestOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequestOutput.ProtoReflect.Descriptor instead.
func (*MergeRequestOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{13}
}

func (x *MergeRequestOutput) GetMrId() int32 {
	if x != nil {
		return x.MrId
	}
	return 0
}

func (x *MergeRequestOutput) GetMrIid() int32 {
	if x != nil {
		return x.MrIid
	}
	return 0
}

func (x *MergeRequestOutput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MergeRequestOutput) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MergeRequestOutput) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *MergeRequestOutput) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *MergeRequestOutput) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

func (x *MergeRequestOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MRCommentOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commented     bool                   `protobuf:"varint,1,opt,name=commented,proto3" json:"commented,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	MrIid         int32                  `protobuf:"varint,3,opt,name=mr_iid,json=mrIid,proto3" json:"mr_iid,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRCommentOutput) Reset() {
	*x = MRCommentOutput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRCommentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRCommentOutput) ProtoMessage() {}

func (x *MRCommentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRCommentOutput.ProtoReflect.Descriptor instead.
func (*MRCommentOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{14}
}

func (x *MRCommentOutput) GetCommented() bool {
	if x != nil {
		return x.Commented
	}
	return false
}

func (x *MRCommentOutput) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *MRCommentOutput) GetMrIid() int32 {
	if x != nil {
		return x.MrIid
	}
	return 0
}

func (x *MRCommentOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ParseWebhookOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parsed        bool                   `protobuf:"varint,1,opt,name=parsed,proto3" json:"parsed,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseWebhookOutput) Reset() {
	*x = ParseWebhookOutput{}
	mi := &file_internal_contracts_gitlab_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseWebhookOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseWebhookOutput) ProtoMessage() {}

func (x *ParseWebhookOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gitlab_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseWebhookOutput.ProtoReflect.Descriptor instead.
func (*ParseWebhookOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gitlab_proto_rawDescGZIP(), []int{15}
}

func (x *ParseWebhookOutput) GetParsed() bool {
	if x != nil {
		return x.Parsed
	}
	return false
}

func (x *ParseWebhookOutput) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ParseWebhookOutput) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ParseWebhookOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_gitlab_proto protoreflect.FileDescriptor

const file_internal_contracts_gitlab_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/contracts/gitlab.proto\x12\x1aworkflow.plugins.gitlab.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x85\x01\n" +
	"\rWebhookConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06events\x18\x04 \x03(\tR\x06events\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\"<\n" +
	"\x12GitLabClientConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x89\x02\n" +
	"\x15TriggerPipelineConfig\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12^\n" +
	"\tvariables\x18\x05 \x03(\v2@.workflow.plugins.gitlab.v1.TriggerPipelineConfig.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x14TriggerPipelineInput\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12]\n" +
	"\tvariables\x18\x04 \x03(\v2?.workflow.plugins.gitlab.v1.TriggerPipelineInput.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x14PipelineStatusConfig\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\x05R\n" +
	"pipelineId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"f\n" +
	"\x13PipelineStatusInput\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\x05R\n" +
	"pipelineId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xde\x01\n" +
	"\x18CreateMergeRequestConfig\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12#\n" +
	"\rsource_branch\x18\x02 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\x03 \x01(\tR\ftargetBranch\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\"\xcb\x01\n" +
	"\x17CreateMergeRequestInput\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12#\n" +
	"\rsource_branch\x18\x02 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\x03 \x01(\tR\ftargetBranch\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"~\n" +
	"\x0fMRCommentConfig\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x15\n" +
	"\x06mr_iid\x18\x02 \x01(\x05R\x05mrIid\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"k\n" +
	"\x0eMRCommentInput\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x15\n" +
	"\x06mr_iid\x18\x02 \x01(\x05R\x05mrIid\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\",\n" +
	"\x12ParseWebhookConfig\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"\x85\x02\n" +
	"\x11ParseWebhookInput\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12+\n" +
	"\x04body\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04body\x12Q\n" +
	"\x06fields\x18\x03 \x03(\v29.workflow.plugins.gitlab.v1.ParseWebhookInput.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x0ePipelineOutput\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\x05R\n" +
	"pipelineId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\tR\x03sha\x12\x17\n" +
	"\aweb_url\x18\x05 \x01(\tR\x06webUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\xe5\x01\n" +
	"\x12MergeRequestOutput\x12\x13\n" +
	"\x05mr_id\x18\x01 \x01(\x05R\x04mrId\x12\x15\n" +
	"\x06mr_iid\x18\x02 \x01(\x05R\x05mrIid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12#\n" +
	"\rsource_branch\x18\x05 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\x06 \x01(\tR\ftargetBranch\x12\x17\n" +
	"\aweb_url\x18\a \x01(\tR\x06webUrl\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"v\n" +
	"\x0fMRCommentOutput\x12\x1c\n" +
	"\tcommented\x18\x01 \x01(\bR\tcommented\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x15\n" +
	"\x06mr_iid\x18\x03 \x01(\x05R\x05mrIid\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x94\x01\n" +
	"\x12ParseWebhookOutput\x12\x16\n" +
	"\x06parsed\x18\x01 \x01(\bR\x06parsed\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBLZJgithub.com/GoCodeAlone/workflow-plugin-gitlab/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_gitlab_proto_rawDescOnce sync.Once
	file_internal_contracts_gitlab_proto_rawDescData []byte
)

func file_internal_contracts_gitlab_proto_rawDescGZIP() []byte {
	file_internal_contracts_gitlab_proto_rawDescOnce.Do(func() {
		file_internal_contracts_gitlab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_gitlab_proto_rawDesc), len(file_internal_contracts_gitlab_proto_rawDesc)))
	})
	return file_internal_contracts_gitlab_proto_rawDescData
}

var file_internal_contracts_gitlab_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_contracts_gitlab_proto_goTypes = []any{
	(*WebhookConfig)(nil),            // 0: workflow.plugins.gitlab.v1.WebhookConfig
	(*GitLabClientConfig)(nil),       // 1: workflow.plugins.gitlab.v1.GitLabClientConfig
	(*TriggerPipelineConfig)(nil),    // 2: workflow.plugins.gitlab.v1.TriggerPipelineConfig
	(*TriggerPipelineInput)(nil),     // 3: workflow.plugins.gitlab.v1.TriggerPipelineInput
	(*PipelineStatusConfig)(nil),     // 4: workflow.plugins.gitlab.v1.PipelineStatusConfig
	(*PipelineStatusInput)(nil),      // 5: workflow.plugins.gitlab.v1.PipelineStatusInput
	(*CreateMergeRequestConfig)(nil), // 6: workflow.plugins.gitlab.v1.CreateMergeRequestConfig
	(*CreateMergeRequestInput)(nil),  // 7: workflow.plugins.gitlab.v1.CreateMergeRequestInput
	(*MRCommentConfig)(nil),          // 8: workflow.plugins.gitlab.v1.MRCommentConfig
	(*MRCommentInput)(nil),           // 9: workflow.plugins.gitlab.v1.MRCommentInput
	(*ParseWebhookConfig)(nil),       // 10: workflow.plugins.gitlab.v1.ParseWebhookConfig
	(*ParseWebhookInput)(nil),        // 11: workflow.plugins.gitlab.v1.ParseWebhookInput
	(*PipelineOutput)(nil),           // 12: workflow.plugins.gitlab.v1.PipelineOutput
	(*MergeRequestOutput)(nil),       // 13: workflow.plugins.gitlab.v1.MergeRequestOutput
	(*MRCommentOutput)(nil),          // 14: workflow.plugins.gitlab.v1.MRCommentOutput
	(*ParseWebhookOutput)(nil),       // 15: workflow.plugins.gitlab.v1.ParseWebhookOutput
	nil,                              // 16: workflow.plugins.gitlab.v1.TriggerPipelineConfig.VariablesEntry
	nil,                              // 17: workflow.plugins.gitlab.v1.TriggerPipelineInput.VariablesEntry
	nil,                              // 18: workflow.plugins.gitlab.v1.ParseWebhookInput.FieldsEntry
	(*structpb.Struct)(nil),          // 19: google.protobuf.Struct
	(*structpb.Value)(nil),           // 20: google.protobuf.Value
}
var file_internal_contracts_gitlab_proto_depIdxs = []int32{
	16, // 0: workflow.plugins.gitlab.v1.TriggerPipelineConfig.variables:type_name -> workflow.plugins.gitlab.v1.TriggerPipelineConfig.VariablesEntry
	17, // 1: workflow.plugins.gitlab.v1.TriggerPipelineInput.variables:type_name -> workflow.plugins.gitlab.v1.TriggerPipelineInput.VariablesEntry
	19, // 2: workflow.plugins.gitlab.v1.ParseWebhookInput.body:type_name -> google.protobuf.Struct
	18, // 3: workflow.plugins.gitlab.v1.ParseWebhookInput.fields:type_name -> workflow.plugins.gitlab.v1.ParseWebhookInput.FieldsEntry
	19, // 4: workflow.plugins.gitlab.v1.ParseWebhookOutput.payload:type_name -> google.protobuf.Struct
	20, // 5: workflow.plugins.gitlab.v1.ParseWebhookInput.FieldsEntry.value:type_name -> google.protobuf.Value
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_contracts_gitlab_proto_init() }
func file_internal_contracts_gitlab_proto_init() {
	if File_internal_contracts_gitlab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_gitlab_proto_rawDesc), len(file_internal_contracts_gitlab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_gitlab_proto_goTypes,
		DependencyIndexes: file_internal_contracts_gitlab_proto_depIdxs,
		MessageInfos:      file_internal_contracts_gitlab_proto_msgTypes,
	}.Build()
	File_internal_contracts_gitlab_proto = out.File
	file_internal_contracts_gitlab_proto_goTypes = nil
	file_internal_contracts_gitlab_proto_depIdxs = nil
}
